#!/bin/bash

git clone https://github.com/pierre-minerva/capstone
source capstone/capstone-env/bin/activate

sudo apt update
sudo apt install mysql-server -y

sudo mysql <<EOF
CREATE DATABASE opt_alg
CREATE USER 'djangouser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
GRANT ALL ON opt_alg.* TO 'djangouser'@'localhost';
FLUSH PRIVILEGES;
EOF

sudo echo "
[client]
database = opt_alg
user = djangouser
password = password
default-character-set = utf8" >> /etc/mysql/my.cnf

sudo systemctl daemon-reload
sudo systemctl restart mysql

sudo apt install libmysqlclient-dev default-libmysqlclient-dev -y
sudo apt-get install gcc python3-dev -y

apt install python3-pip -y
pip install -r capstone/python-requirements.txt

python3 capstone/capsite/manage.py makemigrations
python3 capstone/capsite/manage.py migrate
python3 capstone/capsite/manage.py createsuperuser

sudo ufw allow 8000

python3 capstone/capsite/optalg/db_initialization.py

sudo apt-get install apache2 -y
sudo apt-get install libapache2-mod-wsgi-py3 -y

sudo cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/capstone.conf

echo "
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port t>
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with 'a2disconf'.
        #Include conf-available/serve-cgi-bin.conf

        Alias /static /root/capstone/capsite/optalg/static
        <Directory /root/capstone/capsite/optalg/static>
                Require all granted
        </Directory>

        Alias /static /root/capstone/capsite/optalg/media
        <Directory /root/capstone/capsite/optalg/media>
                Require all granted
        </Directory>

        <Directory /root/capstone/capsite/capsite>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory

        WSGIScriptAlias / /root/capstone/capsite/capsite/wsgi.py
        WSGIDaemonProcess capstone_app python-path=/root/capstone/capsite >
        WSGIProcessGroup capstone_app
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

" > /etc/apache2/sites-available/capstone.conf

sudo a2ensite capstone
sudo a2dissite 000-default.conf

sudo chown -R :www-data /var/lib/mysql
sudo chmod -R 664 /var/lib/mysql
sudo chown -R :www-data capstone

sudo ufw delete allow 8000
sudo ufw allow http/tcp
