version: "3.8"

services:
  web:
    build: 
      context: ./capsite
      dockerfile: Dockerfile.prod
    command: gunicorn capsite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/optalg/static
    expose:
      - 8000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mysql
      MYSQL_DATABASE_HOST: mysql
      MYSQL_DATABASE_PORT: 3306

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume: