version: "3.8"

services:
  web:
    build: 
      context: ./capsite
      dockerfile: Dockerfile.prod
    command: gunicorn capsite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/optalg/static
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mysql

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume: