services:
  app:
    container_name: optalg
    image: python:3.8
    build: .
    command: gunicorn -w 1 -b :8000 app:app
    ports:
      - 8000:8000
    working_dir: /capsite
    volumes:
      - ./capsite:/capsite
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: mysql
    depends_on:
      - mysql
    deploy:
      replicas: 2
      restart_policy:
        condition: "on-failure"

  mysql:
    image: mysql:8.0
    volumes:
      - optalg-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mysql

  nginx:
    container_name: nginx
    restart: always
    build ./nginx
    ports:
      - "80:80"
    depends_on: app

volumes:
  optalg-mysql-data: