version: "3.8"

services:
  web:
    build: ./capsite
    command: gunicorn capsite.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mysql

volumes:
  mysql_data: