# Generated by Django 3.2.7 on 2022-12-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optalg', '0002_algorithm_edge'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='algorithm',
            index=models.Index(fields=['url'], name='optalg_algo_url_ce547b_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['alg_one', 'alg_two'], name='optalg_edge_alg_one_63f64d_idx'),
        ),
        migrations.AddIndex(
            model_name='frontier',
            index=models.Index(fields=['url'], name='optalg_fron_url_aa61b6_idx'),
        ),
    ]
